### ISSUE TITLE
`full_game.js` :  node_modules/hypercore-protocol/index.js:314 error

### ISSUE THREAD

**Issue by raphael10-collab** [kappa-db/workshop#29]
I tried to execute `full_game.js` in a pc and a laptop connected to the same local network, but this is the output:

    (base) raphy@pc:~/hypercore/kappa-db/workshop$ node full_game.js 
    /home/raphy/hypercore/kappa-db/workshop/node_modules/hypercore-protocol/index.js:314
        if (typeof initiator !== 'boolean') throw new Error('Must specify initiator boolean in replication stream')
                                            ^
    
    Error: Must specify initiator boolean in replication stream
        at new ProtocolStream (/home/raphy/hypercore/kappa-db/workshop/node_modules/hypercore-protocol/index.js:314:47)
        at new Multiplexer (/home/raphy/hypercore/kappa-db/workshop/node_modules/multifeed/mux.js:42:32)
        at Multiplexer (/home/raphy/hypercore/kappa-db/workshop/node_modules/multifeed/mux.js:24:46)
        at Multifeed.replicate (/home/raphy/hypercore/kappa-db/workshop/node_modules/multifeed/index.js:258:13)
        at Kappa.replicate (/home/raphy/hypercore/kappa-db/workshop/node_modules/kappa-core/index.js:125:21)
        at Swarm.<anonymous> (/home/raphy/hypercore/kappa-db/workshop/full_game.js:40:18)
        at Swarm.emit (events.js:315:20)
        at onhandshake (/home/raphy/hypercore/kappa-db/workshop/node_modules/discovery-swarm/index.js:444:10)
        at Socket.readable (/home/raphy/hypercore/kappa-db/workshop/node_modules/length-prefixed-message/index.js:46:5)
    
    
    base) marco@marco-U36SG:~/hypercore/kappa-db/workshop$ node full_game.js 
    /home/marco/hypercore/kappa-db/workshop/node_modules/kappa-core/node_modules/hypercore-protocol/index.js:336
        if (typeof initiator !== 'boolean') throw new Error('Must specify initiator boolean in replication stream')
                                            ^
    
    Error: Must specify initiator boolean in replication stream
        at new ProtocolStream (/home/marco/hypercore/kappa-db/workshop/node_modules/kappa-core/node_modules/hypercore-protocol/index.js:336:47)
        at new Multiplexer (/home/marco/hypercore/kappa-db/workshop/node_modules/kappa-core/node_modules/multifeed/mux.js:42:32)
        at Multiplexer (/home/marco/hypercore/kappa-db/workshop/node_modules/kappa-core/node_modules/multifeed/mux.js:24:46)
        at Multifeed.replicate (/home/marco/hypercore/kappa-db/workshop/node_modules/kappa-core/node_modules/multifeed/index.js:258:13)
        at Kappa.replicate (/home/marco/hypercore/kappa-db/workshop/node_modules/kappa-core/index.js:125:21)
        at Swarm.<anonymous> (/home/marco/hypercore/kappa-db/workshop/full_game.js:40:18)
        at Swarm.emit (events.js:376:20)
        at onhandshake (/home/marco/hypercore/kappa-db/workshop/node_modules/discovery-swarm/index.js:444:10)
        at Socket.readable (/home/marco/hypercore/kappa-db/workshop/node_modules/length-prefixed-message/index.js:46:5)
        at Socket.emit (events.js:376:20)

How to solve the problem?

**Comment by hackergrrl** [comment]
This error looks like there is a mismatch between the versions of some of the dependencies. Try
1. `git fetch`ing from the latest `master`
2. wiping your `node_modules/` directory
3. run `npm install` again

**Comment by raphael10-collab** [comment]
Thank you .
